name: php55w
builds:
  webtatic-el7:
    target: el7-development
    arch: [x86_64]
  webtatic-el6:
    target: el6-development
    arch: [x86_64, i386]
  webtatic-el5:
    target: el5-development
    arch: [x86_64, i386]
